config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  resources :projects, only: [:index, :show, :edit, :update] do
    member do 
      post :collaborators
    end

    resources :tickets do
      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
    resources :users do
      member do
        patch :archive
      end
    end
  end

  namespace :api do
    resources :projects do
      resources :tickets
    end
  end
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "BandCamp", root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= "active" if current_page? ("/") %>">
          <%= link_to "Home", root_path %>
        </li>
        <% if current_user.try(:is_admin?) %>
        <li><%= link_to "Admin", admin_root_path %></li>
        <% end %>

        <% unless user_signed_in? %>
          <li class="<%= "active" if current_page?("/users/sign_up") %>">
            <%= link_to "Sign up", new_user_registration_path %>
          </li>
           <li class="<%= "active" if current_page?("/users/sign_in") %>">
            <%= link_to "Sign in", new_user_session_path %>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li> <p class="navbar-text"> Signed in as <%= current_user.email %> </p> </li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>