config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  resources :projects, only: [:index, :show, :edit, :update] do
    member do 
      post :collaborators
    end

    resources :tickets do
      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
    resources :users do
      member do
        patch :archive
      end
    end
  end

  namespace :api do
    resources :projects do
      resources :tickets
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all

  def has_member?(user)
  	roles.exists?(user_id: user)
  end

  def has_manager?(user)
  	roles.exists?(user_id: user, role: 2)
  end

  def has_editor?(user)
  	roles.exists?(user_id: user, role: 1)
  end

  def has_viewer?(user)
  	roles.exists?(user_id: user, role: 0)
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController


  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been created."
      render "new"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/api/projects_controller.rb
class API::ProjectsController < API::ApplicationController
  before_action :project_lookup, only: [:show, :update, :destroy]
  def index
    @projects = policy_scope(Project)
    render json: @projects
  end

  def show
    authorize @project, :show?
    render json: @project
  end

  def create
    @project = Project.new(project_params)
    authorize @project, :create?

    if @project.save
      render json: @project, status: 201
    else
      render json: { errors: @project.errors.full_messages }, status: 422
    end
  end

  def update
    authorize @project, :update?

    if @project.update(project_params)
      render json: @project, status: 201
    else
      render json: { errors: @project.errors.full_messages }, status: 422
    end
  end

  def destroy
    authorize @project, :destroy?


    @project.destroy
    render json: {  success: "Project has been deleted."   }, status: 202
  end

  private

  def project_lookup
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: { errors: "Project not found" }, status: 404
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :project_lookup, only: [:edit, :show, :update, :collaborators]

	def index
		@projects = policy_scope(Project)
	end

	def edit
		authorize @project, :update?
		@available_users = User.all
	end

	def show
		authorize @project, :show?
	end

	def update
		authorize @project, :update?
		if @project.update(project_params)
		   flash[:notice] = "Project has been updated."
		   redirect_to @project
		else
		  flash.now[:alert] = "Project has not been updated."
		  render "edit"
		end
	end

	def collaborators
		authorize @project, :update?
		
		role_role = params.fetch(:roles, [])
	end

	private

	def project_params
		params.require(:project).permit(:name, :description)
	end

	def project_lookup
		@project = Project.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		flash[:alert] = "The project you were looking for could not be found."
		redirect_to projects_path
	end
end

app/views/projects/_collaborators.html.erb
<h4>Add Collaborators</h4>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <% if @project.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@project.errors.count, "error") %>
     prohibited this project from being saved:</h2>
     <ul>
       <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
       <% end %>
    </ul>
  </div>
<% end %>

  <%= f.input :name %>
  <%= f.input  :description %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1>Edit Project
	      <small><%= @project.name %></small>
	  </h1>
	</div>
	<%= render "form", project: @project %>

	<%= render "collaborators", project: @project, user: @available_users %>
</div>

app/views/projects/index.html.erb
<header>
	<h1>Projects</h1>
</header>
<% if current_user.try(:is_admin?) %>
<ul class="actions">
	<li>
    <%= link_to new_admin_project_path, class: "new" do %>
      <i class="fa fa-plus"></i> New Project
    <% end %>
	</li>
</ul>
<% end %>

<div id="projects">
	<% @projects.each do |project| %>
		<h2><%= link_to project.name, project %></h2>
		<p><%= project.description %></p>
	<% end %>
</div>

app/views/projects/new.html.erb
<header>
	<h1>New Project</h1>
</header>
<%= render "form", project: @project %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<header>
	<h1><%= @project.name %></h1>
	<p><%= @project.description %></p>
</header>
<ul class="actions">
	<% if policy(@project).update? %>
	<li>
		<%= link_to edit_project_path(@project), class: "edit" do %>
			<i class="fa fa-pencil"></i>Edit Project
		<% end %>
	</li>
	<% end %>
	<% if current_user.try(:is_admin?) %>
	<li>
		<%= link_to  admin_project_path(@project), class: "delete", method: :delete, data: { confirm: "Are you sure you want to delete this project" } do %>
			<i class="fa fa-trash"></i>Delete Project
		<% end %>
	</li>
	<% end %>
	<% if policy(Ticket.new(project: @project)).create? %>	
		<li><%= link_to "New Ticket", new_project_ticket_path(@project), class: "new" %></li>
	<% end %>
</ul>

<ul id="tickets">
	<% @project.tickets.each do |ticket| %>
		<li>
			#<%= ticket.id %> - 
			<%= link_to ticket.name, [@project, ticket] %>
			<%= render ticket.state if ticket.state %>
		</li>
	<% end %>
</ul>