config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  resources :projects, only: [:index, :show, :edit, :update] do
    member do 
      post :collaborators
    end

    resources :tickets do
      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]

  namespace :admin do
    root "application#index"
    resources :projects, only: [:new, :create, :destroy]
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
    resources :users do
      member do
        patch :archive
      end
    end
  end

  namespace :api do
    resources :projects do
      resources :tickets
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :tag_tickets
	has_many :tickets, :through => :tag_tickets
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def remove
    @ticket = Ticket.find(params[:ticket_id])
    @tag = Tag.find(params[:id])
    authorize @ticket, :tag?

    @ticket.tags.destroy(@tag)
    head :ok
  end
end

app/views/tags/_form.html.erb
	<%= f.input :tag_names, label: "Tags" %>

app/views/tags/_tag.html.erb
<div class="tag">
	<% if policy(ticket).tag? %>
		<%= link_to "<span></span>".html_safe, remove_ticket_tag_path(ticket, tag), 
			method: :delete, remote: true,  class: "remove", title: "remove" %>
	<% end %>
	<%= tag.name %>
</div>